
services:
  sharpconsole.simple:
    build:
      context: ./SharpConsole.Simple
      dockerfile: Dockerfile
    container_name: sharpconsole.simple
    volumes:
      - ./SharpConsole.Simple:/src
    networks:
      - sharpconsole-network
  sharpconsole.entity.inmemory:
    build:
      context: ./SharpConsoleExamples.EntityInMemory
      dockerfile: Dockerfile
    container_name: sharpconsole.entity.inmemory
    volumes:
      - ./SharpConsoleExamples.EntityInMemory:/src
    networks:
      - sharpconsole-network

networks:
  sharpconsole-network:
    driver: bridge
