
services:
  sharpconsole.examples.simple:
    build:
      context: ./SharpConsoleExamples.Simple
      dockerfile: Dockerfile
    container_name: sharpconsole.simple
    volumes:
      - ./SharpConsoleExamples.Simple:/src
    networks:
      - sharpconsole-examples-network
  sharpconsole.examples.entity-inmemory:
    build:
      context: ./SharpConsoleExamples.EntityInMemory
      dockerfile: Dockerfile
    container_name: sharpconsole.entity.inmemory
    volumes:
      - ./SharpConsoleExamples.EntityInMemory:/src
    networks:
      - sharpconsole-examples-network

networks:
  sharpconsole-examples-network:
    driver: bridge
